import localFont from "next/font/local";
import "./globals.css";
import {Poppins, Poppins} from 'next/font/google'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "SkySense",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets:["latin"],
  weight: ['400', '500', '700'],
  style: ['normal', 'italic']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>{children}
      </body>
    </html>
  );
}
